### ISSUE TITLE
请教requestIdleCallback执行条件

### ISSUE THREAD

**Issue by l1shu** [wqhui/blog#24]
文中说如果不需要渲染 则后面的步骤都不会执行，但是后文又说 requestIdleCallback 是在 hasARenderingOpportunity 为false 时执行，这里是不是矛盾了？怎么理解呢？

**Comment by wqhui** [comment]
感谢提问，不过可以直接在对应的文章下就可以直接评论哈。这个issue我先关闭。
然后是问题，不需要渲染的情况下，是后面渲染相关的步骤不会执行，不是后面所有的步骤；不需要渲染，则`hasARenderingOpportunity`就是为`false` ，所以 `requestIdleCallback`是会执行的。
